### ISSUE TITLE
PS3 Games not loading via WebMan MOD OR MMCM!

### ISSUE THREAD

**Issue by davedoc1984** [danmons/retronas#129] opened 2022-03-02 17:58 UTC
Whilst WebMan MOD is picking up the games I have stored on my retronas. None of the PS3 games are loading up (they did work previously without issue). 

PSX ISO's work ok but PS3 games do not load.

PS3 is a CECHA00 plugged in via Ethernet and is running latest WebMan MOD. retronas is on a Pi 4B via Gigabit Ethernet.

**Comment by davedoc1984** [comment] 2022-03-02 18:17
When attempting to load a PS3 game... I am seeing this happen in the log something is broken.

![image](https://user-images.githubusercontent.com/97349996/156423475-e11d3ae4-a504-4de1-bd4d-fdd098bbf214.png)

**Comment by davedoc1984** [comment] 2022-03-03 11:01
Just to add further detail. I have since completely wiped my SD Card and started again. Reinstalled retronas and the various components needed (e.g. Samba) and the PS2, PS3 and MiSTer elements. The same thing still happens so an update at some point has broken the PS3 functionality with loading PS3 games via retronas.

**Comment by sairuk** [comment] 2022-03-04 11:38
That output looks like its from ps3netsrv, that doesn't look like anything RetroNAS will be doing.

I have just purchased a PS3, providing it continues to work (I have 3 dead ones) and I can mod it i will be able to troubleshoot these issues further.

**Comment by davedoc1984** [comment] 2022-03-05 21:32
Is there anything that can be done for ps3netsrv specifically?

**Comment by sairuk** [comment] 2022-03-05 22:27
Until my ps3 arrives and is setup, I can't do much more in this space, but I took a look around github for other issues. Hopefully other will chime in.

From my github search this looks to be a potential ps3netsrv problem with the RPI platform specifically or at least their choice of compilation flags/tooling again.

I am going to assume ps3netsrv is crashing similar to others who have reported "Alignment trap: not handling instruction" across github. You will need to collect data from your system and report it to the upstream to the project to have it solved there, from reading other reports it has something to do with the way structs are handled. 

https://github.com/aldostools/webMAN-MOD

RetroNAS compile and setup up the existing project, we don't do anything at the code level. 

Alternatively 
- You could try and run an update on the pi
- What version of the RaspiOS are you running? try switching to the Raspberry Pi OS 64bit bullseye image on another SD card and setup just the ps3netsrv service and report back.

Until I get have a PS3 i'm not going to be able to debug it any further to report upstream.

**Comment by danmons** [comment] 2022-03-09 19:24
Potentially an upstream issue. I'm hoping to have my PS3 testing system back online this weekend after flooding damage last week, and can do more testing then too. 

Might be a case of rolling back to a previous release of ps3netsrv rather than just grabbing the latest one.

**Comment by davedoc1984** [comment] 2022-03-09 19:37
Is there a command I can run in terminal to roll back ps3netsrv?

**Comment by danmons** [comment] 2022-03-09 23:28
> Is there a command I can run in terminal to roll back ps3netsrv?

Not yet.  RetroNAS currently grabs the most recent stable release from upstream and installs that.  

I'll change the installer so that by default it keeps just grabbing the latest, but I'll add in a command flag where you can specify the build number and override it to test any version you like.  Probably aiming for the weekend, as I'm working 16 hour days for the next 2 days. 

I'll update this thread when it's ready, and add instructions in the wiki on how to do that.

**Comment by davedoc1984** [comment] 2022-03-18 17:20
Thanks Dan.

**Comment by sairuk** [comment] 2022-03-30 21:54
Can you list a title that this specifically happened with so I can attempt to reproduce it here?

Main project has been extremely helpful fixing another issue we were having, so I'd like to give this a go as well. I will need to reproduce before I can provide info

**Comment by sairuk** [comment] 2022-04-01 13:42
I have also updated the [wiki](https://github.com/danmons/retronas/wiki/ps3netsrv) with troubleshooting steps

**Comment by davedoc1984** [comment] 2022-04-04 19:59
Question, how do I install the latest PS3NETSRV on my retronas?

**Comment by sairuk** [comment] 2022-04-04 21:56
Yeh to get the latest version you just reinstall it from the menu, RetroNAS will always grab the latest version available.

Based on further review of your output your OS is kernel dumping when you are trying to run games see [here](https://patchwork.kernel.org/project/linux-arm-kernel/patch/E1goUA9-0003OK-TE@rmk-PC.armlinux.org.uk/#22448729) for where the ARM Linux Kernel added the `8<--- cut here ---` message 

Unfortunately there is not enough information in the screenshot for anyone to successfully debug the issue.

I see you say latest version still do not fix it. Based on your previous issues you were on 32bit raspios, if you are still on 32bit its time to go to 64bit. We are no longer recommending 32bit due to a number of shortcomings we have encountered. 

So try a new OS install on **bullseye raspios 64bit** on another sd of just ps3netsrv (this works for me) and then we can try and help you out because I'm going to assume at this point you are running into the 32bit LFS problems or similar again.

So you understand my thinking, this will either be an OS or ps3netsrv issue and I'm leaning towards **OS** but the more information we can gather the better. I don't think aldo is going to be able to help you debug this yet at a ps3netsrv level based on the information we have.

Linking ps3netsrv issue for reference: https://github.com/aldostools/webMAN-MOD/issues/627

**Comment by danmons** [comment] 2022-04-17 06:56
I've done a clean install today of RetroNAS on both RPiOS 32bit and 64bit, installed ps3netsrv into both, and loaded up games on my PS3.  Everything appears to be working fine. 

@davedoc1984 , are you having any other storage issues?  I've seen one other user with a very large (16TB) USB3 attached HDD in their RPi, running 32bit RPiOS with some very strange errors.  I'm going to echo Sairuk's suggesting here and say that RPiOS 64bit might have to be your next thing to test.

The good news is your HDD can remain as-is, no re-formatting or re-copying needed.  But you will need to install RPiOS fresh using the 64bit version, and re-install the specific tools (ps3netsrv, etc).  As long as your RetroNAS top level path is correct, it'll pick up all your old files where you previously had them.

**Comment by sairuk** [comment] 2022-04-21 05:23
OK in my opinion we've done enough here, its been over 2wks since I my response. closing this

**Closed by sairuk** 2022-04-21 05:23 UTC
Labels: ps3netsrv
