### ISSUE TITLE
Mister FPGA: mame and hbmame roms folder non-standard with upstream project

### ISSUE THREAD

**Issue by xadox-1st** [danmons/retronas#21] opened 2022-02-02 17:58 UTC
The citfs_mount.sh script mounts the mame and hbmame rom folders into the following:

- /media/fat/cifs/mame
- /media/fat/cifs/hbmame

The update_all.sh script somehow downloads the roms to the following folders:

- /media/fat/games/mame
- /media/fat/games/hbmame

But these folders are on the internal sdcard.
Is this a downloader thing or a cifs thing?

**Comment by Peixinho** [comment] 2022-02-03 10:25
I'm having issues with this exact problem

**Comment by xadox-1st** [comment] 2022-02-03 10:34
I created a ticket here, too:
https://github.com/atrac17/MiSTer_MAME_SCRIPTS/issues/35

So maybe the developer of the hbmame & mame downloader will have a look.

**Comment by danmons** [comment] 2022-02-03 12:42
I haven't tested, but I suspect it's a downloader thing.

From memory it has a config section where you can change the path of where files get installed. It might be possible to change that to point to the CIFS mounts. 

I'll try to take a look at this on the weekend.

**Comment by theypsilon** [comment] 2022-02-03 14:35
Hi all, about paths in MiSTer, there is something important we need to clarify:

For CIFS, all MiSTer games folder should be under `/media/fat/cifs/games` by default. 
Not only for `mame/` and `hbmame/` folders but for consoles and computer folders too.
That means, mame roms would go to `/media/fat/cifs/games/mame` and SNES games would go to `/media/fat/cifs/games/SNES`

The firmware is picking the folders following this order:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/852246/152362988-ec421cfd-96b9-46ad-b91d-0e82de07ff8d.png">

And the less prioritized folders are meant to be the default options. That way, users in exceptional cases could opt into overwriting the default behavior without having to mess with the tools.

**Comment by rgb0b** [comment] 2022-02-03 14:48
Would an easier solution be to disable MAME file downloads and just dump the entire MAME and hbMAME library on RetroNAS?  The rom getter script is _so_ helpful for people preserving space on a MicroSD card and it's awesome to only have what you need...
...but if no new roms are being added, RetroNAS users would benefit from having the whole library.  No more downloads needed and the entire libraries should easily fit on someone's storage drive.

**Comment by theypsilon** [comment] 2022-02-03 15:00
The problem is that roms may change between mame versions, and MRAs often require different older mame versions. That's why is still gonna be convenient for users to use some tooling for managing mame roms on MiSTer, that way they won't have to go through all MRAs and hand pick the proper rom for each one of them.

In general, using `/media/fat/cifs/games` should be the default to have a seamless integration with all the other tools.

**Comment by rgb0b** [comment] 2022-02-03 15:04
Okay, I really appreciate the clarification.

**Comment by danmons** [comment] 2022-02-04 02:50
> In general, using `/media/fat/cifs/games` should be the default to have a seamless integration with all the other tools.

Appreciate this guidance. I'll double check the documentation on the weekend and update accordingly.

**Comment by birdybro** [comment] 2022-02-04 20:55
> 
> The firmware is picking the folders following this order: <img alt="image" width="500" src="https://user-images.githubusercontent.com/852246/152362988-ec421cfd-96b9-46ad-b91d-0e82de07ff8d.png">
> 

According to the linked image `/media/fat/cifs` is prioritized first before `/media/fat/cifs/games`. And this is why the current method works for me in the cores. The mame-getter scripts were not checking these folders though. Isn't the source of this problem actually located here:

https://github.com/atrac17/MiSTer_MAME_SCRIPTS/blob/65422c3685902852a303e3e17eaa442064ff16c0/mame-merged-set-getter.sh#L32

ROMNAME is just pointing to a specific folder. It isn't checking for folders the same way the firmware does in the same order.

**Comment by theypsilon** [comment] 2022-02-04 21:27
> > The firmware is picking the folders following this order: <img alt="image" width="500" src="https://user-images.githubusercontent.com/852246/152362988-ec421cfd-96b9-46ad-b91d-0e82de07ff8d.png">
> 
> According to the linked image `/media/fat/cifs` is prioritized first before `/media/fat/cifs/games`. And this is why the current method works for me in the cores to see the folders. However, the mame-getter scripts were not checking these folders though. Isn't the source of this problem actually located here:
> 
> https://github.com/atrac17/MiSTer_MAME_SCRIPTS/blob/65422c3685902852a303e3e17eaa442064ff16c0/mame-merged-set-getter.sh#L32
> 
> ROMNAME is just pointing to a specific folder. It isn't checking for folders the same way the firmware does in the same order.
> 
> Currently this is how RetroNAS organizes them and it works fine:
> 
> ![image](https://user-images.githubusercontent.com/16388068/152601985-8127ba92-8e06-4e23-8a9c-4396990d0779.png)
> 
> The only thing that isn't working fine are the mame-getter scripts.

The MAME Getter behavior is addressed here: https://github.com/atrac17/MiSTer_MAME_SCRIPTS/issues/37
A solution is discussed for that particular problem in that issue.

My comment was aimed to the MiSTer games paths in general.

**Comment by birdybro** [comment] 2022-02-04 21:41
Sorry about that @theypsilon I understand your point now. :)

**Comment by xadox-1st** [comment] 2022-02-05 11:30
Using _update_mame-getter.ini_ and _update_hbmame-getter.ini_ and pointing to another folder is working for me, but for the masses it would be better if its working without changing paths in some ini files.

**Comment by Paradox** [comment] 2022-02-08 15:48
I also created an issue, and a pull request that would fix the getter scripts, a long time ago, but, there seems to be no interest in fixing the issue.
https://github.com/Paradox/MiSTer_MAME_SCRIPTS/commit/69ec66ac5dea1eda92daab35b0899b2dd9676978
https://github.com/atrac17/MiSTer_MAME_SCRIPTS/pull/36

**Comment by sairuk** [comment] 2022-02-13 00:29
I just ran update_all.sh on my MiSTer and the output of the mame getter reports success to the appropriate cifs directory when automounted

```
Skipping MAME files that already exist

Downloading ROMs to /media/fat/cifs/games/mame - Be Patient!!!
```
I am going to close this off now as no additional configuration was required on my side for this to happen, so long as the user has moved to the new mister directory layout by rerunning the installer from retronas

.Quite frankly it surprised me when I ran it, was expecting to have a wiki updated required but it just worked.

**Closed by sairuk** 2022-02-13 00:29 UTC
Labels: MiSTer, samba
