### ISSUE TITLE
USB Drive is still spinning down for me. Issue from before not fixed.

### ISSUE THREAD

**Issue by davedoc1984** [danmons/retronas#112] opened 2022-02-21 15:29 UTC
My USB Hard Drive attached to my Retronas (which is a Pi 4B) still spins down after inactivity. I know some things were put in place before which I had been testing but this issue is still not fixed for me.

![image](https://user-images.githubusercontent.com/97349996/154984991-d95b397b-7a3a-445a-b7df-89fe9dd86ca3.png)

**Comment by davedoc1984** [comment] 2022-02-21 23:04
![image](https://user-images.githubusercontent.com/97349996/155036127-4a999da2-ec38-4439-bcaa-12dbc7f3bd0b.png)

**Comment by sairuk** [comment] 2022-02-22 04:17
that looks to me like it failed to select a sector to read

**Comment by sairuk** [comment] 2022-02-22 10:03
I've commit in a fix for this, raspios has not compiled shuf with large file support 

https://github.com/danmons/retronas/commit/e7dcb0839cc33062149528d2f3c49fcba26d0b78

You should be able to rerun the installer and start and stop the services to test it out

**Comment by sairuk** [comment] 2022-02-24 18:22
@davedoc1984 have you had a chance to test if these changes correct the "Value to large" error?

**Comment by davedoc1984** [comment] 2022-02-28 23:03
Not sure what I need to do? I now have symlinks issues where none of them are working e.g. PS3, PS2 etc which were working previously.

**Comment by sairuk** [comment] 2022-02-28 23:05
I see you've opened a new issue, please restrict that conversation to that issue.

I need to know for this issue if reinstalling the hdparm service and stop/starting it allows it to run without error for you

**Comment by davedoc1984** [comment] 2022-02-28 23:06
I have tried reinstalling HDPARM and this hasn't solved the problem.

**Comment by sairuk** [comment] 2022-02-28 23:12
thanks, please confirm you did the following on the hdparm screen
- Install
- Stop
- Start

Show me the output of the service as you have done previously, so we can attempt to troubleshoot further.

Noting we need to work with your setup to come up with a solution since yours are the only reports of this issue and I cannot reproduce it here.

**Comment by davedoc1984** [comment] 2022-02-28 23:16
Confirmed I did Install, Stop and Start.

This is what I now see on the HDPARM Service

![image](https://user-images.githubusercontent.com/97349996/156074773-d68eabbc-de3b-4739-9df4-c99101c68f55.png)

**Comment by sairuk** [comment] 2022-02-28 23:35
OK so the service is running successfully on your system with the changes I made, looks like I have something to tweak in the counter output.

If reading from the drive is still not preventing the drive from spinning down then my only option is to change the read interval on the timer and see if that helps which is currently every 3-5 minutes

So i'm not going to commit code changes until we've tested it on your system

Please do the following so we can decrease the interval reads are done to the drive to between 30s - 1m

```
sed -i 's/3m/30s/' /usr/lib/systemd/system/hdparm.timer
sed -i 's/2m/30s/' /usr/lib/systemd/system/hdparm.timer
systemctl daemon-reload
systemctl start hdparm.timer
systemctl start hdparm.service
```

This should make the service find and read a sector on a smaller intervale

**Comment by davedoc1984** [comment] 2022-03-02 17:55
Fail I am afraid

![image](https://user-images.githubusercontent.com/97349996/156420083-6c93720a-fd88-4dda-a08a-c02749aebeb2.png)

**Comment by sairuk** [comment] 2022-03-02 20:52
service works ok, as to your hdd i dont see there is anything more RetroNAS can reasonably do. We're issuing a read operation every minute and its still problematic. what drive model is it?

**Comment by sairuk** [comment] 2022-03-06 22:09
If 30-45s interval reads from the drive don't keep it awake there is nothing more than we can do from the RetroNAS side we're going to close this off.

I suggest you try a different enclosure and/or hdd until you find something that works for you or contact the manufacturer about how to correctly disable sleep for whatever drive it is.

**Closed by sairuk** 2022-03-06 22:09 UTC
Labels: storage
